version: "2.6"

services:
 react-app:
  stdin_open: true
  tty: true
  build:
   context: .
  ports:
   - 3000:3000
  volumes:
   - ./src:/app/src
   - /app/node_modules
  environment:
  #  - CHOKIDAR_USEPOLLING=true
   # Para React Scripts 5.x.x+
   - WATCHPACK_POLLING=true
   - REACT_APP_BASE_URL=http://localhost:8000
  #  - REACT_APP_A=Teste-env-var-file
  # env_file:
  #  - ./.env